### ISSUE TITLE
service install but not starting

### ISSUE THREAD

**Issue by potatosips** [xenoncolt/tynispace-rpc#1]
after installing tynispace-rpc, in terminal is says service is running 

![image.png](https://github.com/xenoncolt/tynispace-rpc/assets/118026260/ac414306-1c3e-4409-8efe-fc9770412683)

but in windows service menu, it is not listed as running

![image-1.png](https://github.com/xenoncolt/tynispace-rpc/assets/118026260/1b62ba83-0a88-4451-baf6-67f9e7b798c4)

**Comment by xenoncolt** [comment]
Thanks for creating an issue. I guess I forgot to change the name here...
```
set "psCommand=powershell -Command "Start-Process %DOWNLOAD_DIR%\nssm-2.24\win64\nssm.exe -Verb RunAs -ArgumentList 'start','jellyflix-rpc'""
```
Changing `jellyflix-rpc` to `tynispace-rpc` will work just fine.

**Comment by xenoncolt** [comment]
It would be better to use `net start tynispace-rpc` instead of using `nssm start`. I will fix that in the next update.
